@echo off 
rem *** set_vers.bat, no params
rem  $Date:   23 Mar 2001 16:45:08  $
rem  $Revision:   1.192  $
rem  $Author:   HGASSEL  $
rem  $Logfile:   D:/pvcstemp.log  $
rem
rem

rem for Menu.bat, startup.bat, loadcm.bat 
rem load default MC's: SRAM switch /mc%MAXMC%
set	MAXMC=5739

set vers_nr=373
set manp_vers_nr=373
set ext=00b
set vnr=3
set hnr=7

rem *** MANUALplus SW ***
set sw_nr=349 644-03

rem *** MANUALplus Trainer *** 
rem set sw_nr=334 670-08
